services:
  angular:
    restart: unless-stopped
    build:
      dockerfile: angular.dockerfile
      context: .
    container_name: 'angular'
    ports:
      - '4200:4200'
    volumes:
      - 'angular:/usr/src/app'

volumes:
  angular:
