name: Baixar e executar imagem Docker
on:
  workflow_run:
    workflows: ["Criar e publicar imagem Docker"]
    types:
      - completed
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  download-and-execute-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            docker stop ${{ env.IMAGE_NAME }} || true
            docker rm ${{ env.IMAGE_NAME }} || true
            docker pull ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
            docker run -d ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
